J.J. Watt#HOU
Kwon Alexander#TB
Luke Kuechly#CAR
Bobby Wagner#SEA
Alec Ogletree#LAR
Jason Pierre-Paul#NYG
Joey Bosa#LAC
Olivier Vernon#NYG
Danielle Hunter#MIN
C.J. Mosley#BAL
Telvin Smith#JAC
Jamie Collins#CLE
Aaron Donald#LAR
Calais Campbell#JAC
Sean Lee#DAL
Ryan Shazier#PIT
Carlos Dunlap#CIN
Landon Collins#NYG
Vontaze Burfict#CIN
Everson Griffen#MIN
Keanu Neal#ATL
Cameron Jordan#NO
Benardrick McKinney#HOU
Christian Kirksey#CLE
Deion Jones#ATL
Muhammad Wilkerson#NYJ
Lavonte David#TB
Eric Kendricks#MIN
Johnathan Cyprien#TEN
DeForest Buckner#SF
Ezekiel Ansah#DET
Harrison Smith#MIN
Leonard Williams#NYJ
Jerrell Freeman#CHI
Ndamukong Suh#MIA
Jatavis Brown#LAC
Reshad Jones#MIA
Navorro Bowman#SF
Morgan Burnett#GB
Brandon Graham#PHI
Zach Brown#WAS
Tony Jefferson#BAL
Mark Barron#LAR
Khalil Mack#OAK
Fletcher Cox#PHI
Barry Church#JAC
K.J. Wright#SEA
Myles Garrett#CLE
Kiko Alonso#MIA
T.J. Ward#DEN
Hasean Clinton-Dix#GB
Melvin Ingram#LAC
Kawann Short#CAR
Kurt Coleman#CAR
Eric Weddle#BAL
Sheldon Richardson#NYJ
Karl Joseph#OAK
Kenny Vaccaro#NO
Derrick Johnson#KC
Michael Bennett#SEA
Cameron Wake#MIA
Lawrence Timmons#MIA
Jarrad Davis#DET
Reuben Foster#SF
Jordan Hicks#PHI
Paul Posluszny#JAC
Deone Bucannon#ARI
Geno Atkins#CIN
Chris Conte#TB
Damon Harrison#NYG
Kam Chancellor#SEA
Von Miller#DEN
Malcolm Jenkins#PHI
Eric Berry#KC
Jerry Hughes#BUF
Logan Ryan#TEN
Jamal Adams#NYJ
Su'a Cravens#WAS
Myles Jack#JAC
Kyle Williams#BUF
Tyrann Mathieu#ARI
Trey Flowers#NE
Cliff Avril#SEA
Cameron Heyward#PIT
Vince Williams#PIT
Reggie Ragland#BUF
Brandon Marshall#DEN
Sean Davis#PIT
Linval Joseph#MIN
Kony Ealy#NE
Tahir Whitehead#DET
Thomas Davis#CAR
Keith Tandy#TB
Tavon Wilson#DET
Antoine Bethea#ARI
Robert Quinn#LAR
Preston Brown#BUF
Malik Jackson#JAC
Eric Reid#SF
Avery Williamson#TEN
Daryl Worley#CAR
Byron Jones#DAL
Corey Graham#PHI
Vonn Bell#NO
Micah Hyde#BUF
Akiem Hicks#CHI
Danny Trevathan#CHI
Marcell Dareus#BUF
Bashaud Breeland#WAS
Emmanuel Ogbah#CLE
Jahleel Addae#LAC
Devin McCourty#NE
Darron Lee#NYJ
Clayton Geathers#IND
Ramik Wilson#KC
Frank Clark#SEA
Jurrell Casey#TEN
Shawn Williams#CIN
Denzel Perryman#LAC
Marcus Cooper#CHI
Reggie Nelson#OAK
Justin Houston#KC
Haason Reddick#ARI
Rodney McLeod#PHI
Stephon Tuitt#PIT
Quintin Demps#CHI
Karlos Dansby#ARI
Nigel Bradham#PHI
D.J. Swearinger#WAS
BJ Goodson#NYG
Derek Wolfe#DEN
Mario Addison#CAR
Mike Adams#CAR
Gerald McCoy#TB
Dont'a Hightower#NE
Ron Parker#KC
Patrick Chung#NE
Earl Thomas#SEA
Mason Foster#WAS
Noah Spence#TB
Jaquiski Tartt#SF
Jabrill Peppers#CLE
Vic Beasley#ATL
Will Compton#WAS
Josh Norman#WAS
Marcus Peters#KC
Michael Mitchell#PIT
Demario Davis#NYJ
Maurice Alexander#LAR
Ronald Darby#BUF
Johnathan Hankins#IND